export interface CountryLocalizationEntry {
  en: string;
  ko: string;
  confederation: string;
}

export interface NamedLocalizationEntry {
  name: string;
  shortName: string;
}

export const COUNTRY_TRANSLATIONS: Record<string, CountryLocalizationEntry> = {
  AFR: { en: 'Africa', ko: '아프리카', confederation: '' },
  ALB: { en: 'Albania', ko: '알바니아', confederation: 'UEFA' },
  ALG: { en: 'Algeria', ko: '알제리', confederation: 'CAF' },
  ANG: { en: 'Angola', ko: '앙골라', confederation: 'CAF' },
  ARG: { en: 'Argentina', ko: '아르헨티나', confederation: 'CONMEBOL' },
  AUS: { en: 'Australia', ko: '호주', confederation: 'AFC' },
  AUT: { en: 'Austria', ko: '오스트리아', confederation: 'UEFA' },
  AZE: { en: 'Azerbaijan', ko: '아제르바이잔', confederation: 'UEFA' },
  BEL: { en: 'Belgium', ko: '벨기에', confederation: 'UEFA' },
  BOL: { en: 'Bolivia', ko: '볼리비아', confederation: 'CONMEBOL' },
  BHR: { en: 'Bahrain', ko: '바레인', confederation: 'AFC' },
  BIH: { en: 'Bosnia and Herzegovina', ko: '보스니아 헤르체고비나', confederation: 'UEFA' },
  BLR: { en: 'Belarus', ko: '벨라루스', confederation: 'UEFA' },
  BEN: { en: 'Benin', ko: '베냉', confederation: 'CAF' },
  BFA: { en: 'Burkina Faso', ko: '부르키나파소', confederation: 'CAF' },
  BRA: { en: 'Brazil', ko: '브라질', confederation: 'CONMEBOL' },
  BUL: { en: 'Bulgaria', ko: '불가리아', confederation: 'UEFA' },
  BUR: { en: 'Burkina Faso', ko: '부르키나파소', confederation: 'CAF' },
  CAM: { en: 'Cameroon', ko: '카메룬', confederation: 'CAF' },
  CAN: { en: 'Canada', ko: '캐나다', confederation: 'CONCACAF' },
  CAP: { en: 'Cape Verde', ko: '카보베르데', confederation: 'CAF' },
  CHI: { en: 'China', ko: '중국', confederation: 'AFC' },
  CHN: { en: 'China PR', ko: '중국', confederation: 'AFC' },
  CMR: { en: 'Cameroon', ko: '카메룬', confederation: 'CAF' },
  CON: { en: 'DR Congo', ko: '콩고민주공화국', confederation: 'CAF' },
  COS: { en: 'Costa Rica', ko: '코스타리카', confederation: 'CONCACAF' },
  COT: { en: 'Ivory Coast', ko: '코트디부아르', confederation: 'CAF' },
  CIV: { en: 'Ivory Coast', ko: '코트디부아르', confederation: 'CAF' },
  COL: { en: 'Colombia', ko: '콜롬비아', confederation: 'CONMEBOL' },
  CRO: { en: 'Croatia', ko: '크로아티아', confederation: 'UEFA' },
  CPV: { en: 'Cape Verde', ko: '카보베르데', confederation: 'CAF' },
  CUB: { en: 'Cuba', ko: '쿠바', confederation: 'CONCACAF' },
  CUW: { en: 'Curaçao', ko: '퀴라소', confederation: 'CONCACAF' },
  CZE: { en: 'Czech Republic', ko: '체코', confederation: 'UEFA' },
  DEN: { en: 'Denmark', ko: '덴마크', confederation: 'UEFA' },
  ECU: { en: 'Ecuador', ko: '에콰도르', confederation: 'CONMEBOL' },
  EGY: { en: 'Egypt', ko: '이집트', confederation: 'CAF' },
  ENG: { en: 'England', ko: '잉글랜드', confederation: 'UEFA' },
  EQU: { en: 'Equatorial Guinea', ko: '적도 기니', confederation: 'CAF' },
  ESP: { en: 'Spain', ko: '스페인', confederation: 'UEFA' },
  EUR: { en: 'Europe', ko: '유럽', confederation: '' },
  FIN: { en: 'Finland', ko: '핀란드', confederation: 'UEFA' },
  FIJ: { en: 'Fiji', ko: '피지', confederation: 'OFC' },
  FRA: { en: 'France', ko: '프랑스', confederation: 'UEFA' },
  GAM: { en: 'Gambia', ko: '감비아', confederation: 'CAF' },
  GAB: { en: 'Gabon', ko: '가봉', confederation: 'CAF' },
  GEO: { en: 'Georgia', ko: '조지아', confederation: 'UEFA' },
  GER: { en: 'Germany', ko: '독일', confederation: 'UEFA' },
  GHA: { en: 'Ghana', ko: '가나', confederation: 'CAF' },
  GRE: { en: 'Greece', ko: '그리스', confederation: 'UEFA' },
  GUA: { en: 'Guatemala', ko: '과테말라', confederation: 'CONCACAF' },
  GUY: { en: 'Guyana', ko: '가이아나', confederation: 'CONCACAF' },
  GUM: { en: 'Guam', ko: '괌', confederation: 'AFC' },
  GUI: { en: 'Guinea-Bissau', ko: '기니비사우', confederation: 'CAF' },
  HAI: { en: 'Haiti', ko: '아이티', confederation: 'CONCACAF' },
  HKG: { en: 'Hong Kong, China', ko: '홍콩', confederation: 'AFC' },
  HON: { en: 'Honduras', ko: '온두라스', confederation: 'CONCACAF' },
  HUN: { en: 'Hungary', ko: '헝가리', confederation: 'UEFA' },
  ICE: { en: 'Iceland', ko: '아이슬란드', confederation: 'UEFA' },
  IND: { en: 'India', ko: '인도', confederation: 'AFC' },
  INT: { en: 'International', ko: '국제', confederation: '' },
  IRA: { en: 'Iran', ko: '이란', confederation: 'AFC' },
  IRE: { en: 'Ireland', ko: '아일랜드', confederation: 'UEFA' },
  IRQ: { en: 'Iraq', ko: '이라크', confederation: 'AFC' },
  IRN: { en: 'Iran', ko: '이란', confederation: 'AFC' },
  ISR: { en: 'Israel', ko: '이스라엘', confederation: 'UEFA' },
  ITA: { en: 'Italy', ko: '이탈리아', confederation: 'UEFA' },
  JAM: { en: 'Jamaica', ko: '자메이카', confederation: 'CONCACAF' },
  JAP: { en: 'Japan', ko: '일본', confederation: 'AFC' },
  JOR: { en: 'Jordan', ko: '요르단', confederation: 'AFC' },
  JPN: { en: 'Japan', ko: '일본', confederation: 'AFC' },
  KOR: { en: 'South Korea', ko: '대한민국', confederation: 'AFC' },
  KOS: { en: 'Kosovo', ko: '코소보', confederation: 'UEFA' },
  KSA: { en: 'Saudi Arabia', ko: '사우디아라비아', confederation: 'AFC' },
  MAC: { en: 'North Macedonia', ko: '북마케도니아', confederation: 'UEFA' },
  MAL: { en: 'Mali', ko: '말리', confederation: 'CAF' },
  MAR: { en: 'Morocco', ko: '모로코', confederation: 'CAF' },
  MAS: { en: 'Malaysia', ko: '말레이시아', confederation: 'AFC' },
  MAU: { en: 'Mauritania', ko: '모리타니', confederation: 'CAF' },
  MEX: { en: 'Mexico', ko: '멕시코', confederation: 'CONCACAF' },
  MKD: { en: 'North Macedonia', ko: '북마케도니아', confederation: 'UEFA' },
  MLT: { en: 'Malta', ko: '몰타', confederation: 'UEFA' },
  MON: { en: 'Monaco', ko: '모나코', confederation: '' },
  MNE: { en: 'Montenegro', ko: '몬테네그로', confederation: 'UEFA' },
  MOR: { en: 'Morocco', ko: '모로코', confederation: 'CAF' },
  MOZ: { en: 'Mozambique', ko: '모잠비크', confederation: 'CAF' },
  MYA: { en: 'Myanmar', ko: '미얀마', confederation: 'AFC' },
  NAM: { en: 'Namibia', ko: '나미비아', confederation: 'CAF' },
  NCA: { en: 'Nicaragua', ko: '니카라과', confederation: 'CONCACAF' },
  NCL: { en: 'New Caledonia', ko: '뉴칼레도니아', confederation: 'OFC' },
  NEP: { en: 'Nepal', ko: '네팔', confederation: 'AFC' },
  NET: { en: 'Netherlands', ko: '네덜란드', confederation: 'UEFA' },
  NED: { en: 'Netherlands', ko: '네덜란드', confederation: 'UEFA' },
  NEW: { en: 'New Zealand', ko: '뉴질랜드', confederation: 'OFC' },
  NGA: { en: 'Nigeria', ko: '나이지리아', confederation: 'CAF' },
  NIR: { en: 'Northern Ireland', ko: '북아일랜드', confederation: 'UEFA' },
  NIG: { en: 'Nigeria', ko: '나이지리아', confederation: 'CAF' },
  NOR: { en: 'Norway', ko: '노르웨이', confederation: 'UEFA' },
  NZL: { en: 'New Zealand', ko: '뉴질랜드', confederation: 'OFC' },
  OMA: { en: 'Oman', ko: '오만', confederation: 'AFC' },
  PAN: { en: 'Panama', ko: '파나마', confederation: 'CONCACAF' },
  PAR: { en: 'Paraguay', ko: '파라과이', confederation: 'CONMEBOL' },
  PER: { en: 'Peru', ko: '페루', confederation: 'CONMEBOL' },
  PHI: { en: 'Philippines', ko: '필리핀', confederation: 'AFC' },
  PLE: { en: 'Palestine', ko: '팔레스타인', confederation: 'AFC' },
  POL: { en: 'Poland', ko: '폴란드', confederation: 'UEFA' },
  POR: { en: 'Portugal', ko: '포르투갈', confederation: 'UEFA' },
  PNG: { en: 'Papua New Guinea', ko: '파푸아뉴기니', confederation: 'OFC' },
  PRK: { en: 'Korea DPR', ko: '북한', confederation: 'AFC' },
  PUR: { en: 'Puerto Rico', ko: '푸에르토리코', confederation: 'CONCACAF' },
  QAT: { en: 'Qatar', ko: '카타르', confederation: 'AFC' },
  ROM: { en: 'Romania', ko: '루마니아', confederation: 'UEFA' },
  RUS: { en: 'Russia', ko: '러시아', confederation: 'UEFA' },
  SAU: { en: 'Saudi Arabia', ko: '사우디아라비아', confederation: 'AFC' },
  RSA: { en: 'South Africa', ko: '남아프리카공화국', confederation: 'CAF' },
  SAM: { en: 'Samoa', ko: '사모아', confederation: 'OFC' },
  SCO: { en: 'Scotland', ko: '스코틀랜드', confederation: 'UEFA' },
  SER: { en: 'Serbia', ko: '세르비아', confederation: 'UEFA' },
  SEN: { en: 'Senegal', ko: '세네갈', confederation: 'CAF' },
  SLV: { en: 'El Salvador', ko: '엘살바도르', confederation: 'CONCACAF' },
  SLO: { en: 'Slovakia', ko: '슬로바키아', confederation: 'UEFA' },
  SOL: { en: 'Solomon Islands', ko: '솔로몬 제도', confederation: 'OFC' },
  SOU: { en: 'South Africa', ko: '남아프리카공화국', confederation: 'CAF' },
  SPA: { en: 'Spain', ko: '스페인', confederation: 'UEFA' },
  SVN: { en: 'Slovenia', ko: '슬로베니아', confederation: 'UEFA' },
  SWE: { en: 'Sweden', ko: '스웨덴', confederation: 'UEFA' },
  SWI: { en: 'Switzerland', ko: '스위스', confederation: 'UEFA' },
  SYR: { en: 'Syria', ko: '시리아', confederation: 'AFC' },
  SUI: { en: 'Switzerland', ko: '스위스', confederation: 'UEFA' },
  TAN: { en: 'Tanzania', ko: '탄자니아', confederation: 'CAF' },
  THA: { en: 'Thailand', ko: '태국', confederation: 'AFC' },
  TJK: { en: 'Tajikistan', ko: '타지키스탄', confederation: 'AFC' },
  TPE: { en: 'Chinese Taipei', ko: '중화 타이베이', confederation: 'AFC' },
  TRI: { en: 'Trinidad and Tobago', ko: '트리니다드 토바고', confederation: 'CONCACAF' },
  TUN: { en: 'Tunisia', ko: '튀니지', confederation: 'CAF' },
  TUR: { en: 'Turkey', ko: '터키', confederation: 'UEFA' },
  UAE: { en: 'United Arab Emirates', ko: '아랍에미리트', confederation: 'AFC' },
  UGA: { en: 'Uganda', ko: '우간다', confederation: 'CAF' },
  UKR: { en: 'Ukraine', ko: '우크라이나', confederation: 'UEFA' },
  UNI: { en: 'United States of America', ko: '미국', confederation: 'CONCACAF' },
  URU: { en: 'Uruguay', ko: '우루과이', confederation: 'CONMEBOL' },
  USA: { en: 'United States', ko: '미국', confederation: 'CONCACAF' },
  UZB: { en: 'Uzbekistan', ko: '우즈베키스탄', confederation: 'AFC' },
  VEN: { en: 'Venezuela', ko: '베네수엘라', confederation: 'CONMEBOL' },
  VAN: { en: 'Vanuatu', ko: '바누아투', confederation: 'OFC' },
  VIE: { en: 'Vietnam', ko: '베트남', confederation: 'AFC' },
  WAL: { en: 'Wales', ko: '웨일스', confederation: 'UEFA' },
  ZAM: { en: 'Zambia', ko: '잠비아', confederation: 'CAF' },
};

export const COMPETITION_NAMES_KO: Record<string, NamedLocalizationEntry> = {
  '1-bundesliga': { name: '분데스리가', shortName: '분데스리가' },
  'african-cup-of-nations-international': { name: '아프리카 네이션스컵', shortName: '네이션스컵' },
  bundesliga: { name: '분데스리가', shortName: '분데스리가' },
  'champions-league': { name: 'UEFA 챔피언스리그', shortName: '챔피언스리그' },
  'copa-america-international': { name: '코파 아메리카', shortName: '코파 아메리카' },
  'copa-del-rey': { name: '코파 델 레이', shortName: '코파 델 레이' },
  'fa-women-s-super-league-women': { name: 'FA 여자 슈퍼리그', shortName: 'FA 여자 슈퍼리그' },
  'fifa-u20-world-cup-international-youth': { name: 'FIFA U-20 월드컵', shortName: 'U-20 월드컵' },
  'fifa-world-cup-international': { name: 'FIFA 월드컵', shortName: '월드컵' },
  'indian-super-league': { name: '인도 슈퍼리그', shortName: '인도 슈퍼리그' },
  laliga: { name: '라리가', shortName: '라리가' },
  'la-liga': { name: '라리가', shortName: '라리가' },
  'liga-profesional': { name: '리가 프로페시오날', shortName: '리가 프로페시오날' },
  ligue1: { name: '리그 1', shortName: '리그 1' },
  'ligue-1': { name: '리그 1', shortName: '리그 1' },
  'major-league-soccer': { name: '메이저리그사커', shortName: 'MLS' },
  'north-american-league': { name: '북미 리그', shortName: '북미 리그' },
  'nwsl-women': { name: 'NWSL', shortName: 'NWSL' },
  pl: { name: '프리미어리그', shortName: '프리미어리그' },
  'premier-league': { name: '프리미어리그', shortName: '프리미어리그' },
  seriea: { name: '세리에 A', shortName: '세리에 A' },
  'serie-a': { name: '세리에 A', shortName: '세리에 A' },
  'uefa-euro-international': { name: 'UEFA 유로', shortName: 'UEFA 유로' },
  'uefa-europa-league': { name: 'UEFA 유로파리그', shortName: '유로파리그' },
  'uefa-women-s-euro-international-women': { name: 'UEFA 여자 유로', shortName: 'UEFA 여자 유로' },
  'women-s-world-cup-international-women': { name: '여자 월드컵', shortName: '여자 월드컵' },
};

export const TEAM_NAMES_KO: Record<string, NamedLocalizationEntry> = {
  arsenal: { name: '아스널', shortName: 'ARS' },
  atletico: { name: '아틀레티코 마드리드', shortName: 'ATM' },
  barcelona: { name: '바르셀로나', shortName: 'BAR' },
  'bayer-leverkusen-germany': { name: '바이어 04 레버쿠젠', shortName: 'B04' },
  bayern: { name: '바이에른 뮌헨', shortName: 'BAY' },
  chelsea: { name: '첼시', shortName: 'CHE' },
  dortmund: { name: '보루시아 도르트문트', shortName: 'BVB' },
  inter: { name: '인테르', shortName: 'INT' },
  juventus: { name: '유벤투스', shortName: 'JUV' },
  leipzig: { name: 'RB 라이프치히', shortName: 'RBL' },
  leverkusen: { name: '바이어 레버쿠젠', shortName: 'B04' },
  liverpool: { name: '리버풀', shortName: 'LIV' },
  mancity: { name: '맨체스터 시티', shortName: 'MCI' },
  milan: { name: 'AC 밀란', shortName: 'MIL' },
  monaco: { name: 'AS 모나코', shortName: 'MON' },
  napoli: { name: '나폴리', shortName: 'NAP' },
  psg: { name: '파리 생제르맹', shortName: 'PSG' },
  realmadrid: { name: '레알 마드리드', shortName: 'RMA' },
  sevilla: { name: '세비야', shortName: 'SEV' },
  'werder-bremen-germany': { name: '베르더 브레멘', shortName: 'BRE' },
};
