export interface CountryLocalizationEntry {
  en: string;
  ko: string;
  confederation: string;
}

export interface NamedLocalizationEntry {
  name: string;
  shortName: string;
}

export const COUNTRY_TRANSLATIONS: Record<string, CountryLocalizationEntry> = {
  AFR: { en: 'Africa', ko: '아프리카', confederation: '' },
  ALB: { en: 'Albania', ko: '알바니아', confederation: 'UEFA' },
  ALG: { en: 'Algeria', ko: '알제리', confederation: 'CAF' },
  ANG: { en: 'Angola', ko: '앙골라', confederation: 'CAF' },
  ARG: { en: 'Argentina', ko: '아르헨티나', confederation: 'CONMEBOL' },
  AUS: { en: 'Australia', ko: '호주', confederation: 'AFC' },
  AUT: { en: 'Austria', ko: '오스트리아', confederation: 'UEFA' },
  AZE: { en: 'Azerbaijan', ko: '아제르바이잔', confederation: 'UEFA' },
  BEL: { en: 'Belgium', ko: '벨기에', confederation: 'UEFA' },
  BOL: { en: 'Bolivia', ko: '볼리비아', confederation: 'CONMEBOL' },
  BHR: { en: 'Bahrain', ko: '바레인', confederation: 'AFC' },
  BIH: { en: 'Bosnia and Herzegovina', ko: '보스니아 헤르체고비나', confederation: 'UEFA' },
  BLR: { en: 'Belarus', ko: '벨라루스', confederation: 'UEFA' },
  BEN: { en: 'Benin', ko: '베냉', confederation: 'CAF' },
  BFA: { en: 'Burkina Faso', ko: '부르키나파소', confederation: 'CAF' },
  BRA: { en: 'Brazil', ko: '브라질', confederation: 'CONMEBOL' },
  BUL: { en: 'Bulgaria', ko: '불가리아', confederation: 'UEFA' },
  BUR: { en: 'Burkina Faso', ko: '부르키나파소', confederation: 'CAF' },
  CAM: { en: 'Cameroon', ko: '카메룬', confederation: 'CAF' },
  CAN: { en: 'Canada', ko: '캐나다', confederation: 'CONCACAF' },
  CAP: { en: 'Cape Verde', ko: '카보베르데', confederation: 'CAF' },
  CHI: { en: 'China', ko: '중국', confederation: 'AFC' },
  CHN: { en: 'China PR', ko: '중국', confederation: 'AFC' },
  CMR: { en: 'Cameroon', ko: '카메룬', confederation: 'CAF' },
  CON: { en: 'DR Congo', ko: '콩고민주공화국', confederation: 'CAF' },
  COS: { en: 'Costa Rica', ko: '코스타리카', confederation: 'CONCACAF' },
  COT: { en: 'Ivory Coast', ko: '코트디부아르', confederation: 'CAF' },
  CIV: { en: 'Ivory Coast', ko: '코트디부아르', confederation: 'CAF' },
  COL: { en: 'Colombia', ko: '콜롬비아', confederation: 'CONMEBOL' },
  CRO: { en: 'Croatia', ko: '크로아티아', confederation: 'UEFA' },
  CPV: { en: 'Cape Verde', ko: '카보베르데', confederation: 'CAF' },
  CUB: { en: 'Cuba', ko: '쿠바', confederation: 'CONCACAF' },
  CUW: { en: 'Curaçao', ko: '퀴라소', confederation: 'CONCACAF' },
  CZE: { en: 'Czech Republic', ko: '체코', confederation: 'UEFA' },
  DEN: { en: 'Denmark', ko: '덴마크', confederation: 'UEFA' },
  ECU: { en: 'Ecuador', ko: '에콰도르', confederation: 'CONMEBOL' },
  EGY: { en: 'Egypt', ko: '이집트', confederation: 'CAF' },
  ENG: { en: 'England', ko: '잉글랜드', confederation: 'UEFA' },
  EQU: { en: 'Equatorial Guinea', ko: '적도 기니', confederation: 'CAF' },
  ESP: { en: 'Spain', ko: '스페인', confederation: 'UEFA' },
  EUR: { en: 'Europe', ko: '유럽', confederation: '' },
  FIN: { en: 'Finland', ko: '핀란드', confederation: 'UEFA' },
  FIJ: { en: 'Fiji', ko: '피지', confederation: 'OFC' },
  FRA: { en: 'France', ko: '프랑스', confederation: 'UEFA' },
  GAM: { en: 'Gambia', ko: '감비아', confederation: 'CAF' },
  GAB: { en: 'Gabon', ko: '가봉', confederation: 'CAF' },
  GEO: { en: 'Georgia', ko: '조지아', confederation: 'UEFA' },
  GER: { en: 'Germany', ko: '독일', confederation: 'UEFA' },
  GHA: { en: 'Ghana', ko: '가나', confederation: 'CAF' },
  GRE: { en: 'Greece', ko: '그리스', confederation: 'UEFA' },
  GUA: { en: 'Guatemala', ko: '과테말라', confederation: 'CONCACAF' },
  GUY: { en: 'Guyana', ko: '가이아나', confederation: 'CONCACAF' },
  GUM: { en: 'Guam', ko: '괌', confederation: 'AFC' },
  GUI: { en: 'Guinea-Bissau', ko: '기니비사우', confederation: 'CAF' },
  HAI: { en: 'Haiti', ko: '아이티', confederation: 'CONCACAF' },
  HKG: { en: 'Hong Kong, China', ko: '홍콩', confederation: 'AFC' },
  HON: { en: 'Honduras', ko: '온두라스', confederation: 'CONCACAF' },
  HUN: { en: 'Hungary', ko: '헝가리', confederation: 'UEFA' },
  ICE: { en: 'Iceland', ko: '아이슬란드', confederation: 'UEFA' },
  IND: { en: 'India', ko: '인도', confederation: 'AFC' },
  INT: { en: 'International', ko: '국제', confederation: '' },
  IRA: { en: 'Iran', ko: '이란', confederation: 'AFC' },
  IRE: { en: 'Ireland', ko: '아일랜드', confederation: 'UEFA' },
  IRQ: { en: 'Iraq', ko: '이라크', confederation: 'AFC' },
  IRN: { en: 'Iran', ko: '이란', confederation: 'AFC' },
  ISR: { en: 'Israel', ko: '이스라엘', confederation: 'UEFA' },
  ITA: { en: 'Italy', ko: '이탈리아', confederation: 'UEFA' },
  JAM: { en: 'Jamaica', ko: '자메이카', confederation: 'CONCACAF' },
  JAP: { en: 'Japan', ko: '일본', confederation: 'AFC' },
  JOR: { en: 'Jordan', ko: '요르단', confederation: 'AFC' },
  JPN: { en: 'Japan', ko: '일본', confederation: 'AFC' },
  KOR: { en: 'South Korea', ko: '대한민국', confederation: 'AFC' },
  KOS: { en: 'Kosovo', ko: '코소보', confederation: 'UEFA' },
  KSA: { en: 'Saudi Arabia', ko: '사우디아라비아', confederation: 'AFC' },
  MAC: { en: 'North Macedonia', ko: '북마케도니아', confederation: 'UEFA' },
  MAL: { en: 'Mali', ko: '말리', confederation: 'CAF' },
  MAR: { en: 'Morocco', ko: '모로코', confederation: 'CAF' },
  MAS: { en: 'Malaysia', ko: '말레이시아', confederation: 'AFC' },
  MAU: { en: 'Mauritania', ko: '모리타니', confederation: 'CAF' },
  MEX: { en: 'Mexico', ko: '멕시코', confederation: 'CONCACAF' },
  MKD: { en: 'North Macedonia', ko: '북마케도니아', confederation: 'UEFA' },
  MLT: { en: 'Malta', ko: '몰타', confederation: 'UEFA' },
  MON: { en: 'Monaco', ko: '모나코', confederation: '' },
  MNE: { en: 'Montenegro', ko: '몬테네그로', confederation: 'UEFA' },
  MOR: { en: 'Morocco', ko: '모로코', confederation: 'CAF' },
  MOZ: { en: 'Mozambique', ko: '모잠비크', confederation: 'CAF' },
  MYA: { en: 'Myanmar', ko: '미얀마', confederation: 'AFC' },
  NAM: { en: 'Namibia', ko: '나미비아', confederation: 'CAF' },
  NCA: { en: 'Nicaragua', ko: '니카라과', confederation: 'CONCACAF' },
  NCL: { en: 'New Caledonia', ko: '뉴칼레도니아', confederation: 'OFC' },
  NEP: { en: 'Nepal', ko: '네팔', confederation: 'AFC' },
  NET: { en: 'Netherlands', ko: '네덜란드', confederation: 'UEFA' },
  NED: { en: 'Netherlands', ko: '네덜란드', confederation: 'UEFA' },
  NEW: { en: 'New Zealand', ko: '뉴질랜드', confederation: 'OFC' },
  NGA: { en: 'Nigeria', ko: '나이지리아', confederation: 'CAF' },
  NIR: { en: 'Northern Ireland', ko: '북아일랜드', confederation: 'UEFA' },
  NIG: { en: 'Nigeria', ko: '나이지리아', confederation: 'CAF' },
  NOR: { en: 'Norway', ko: '노르웨이', confederation: 'UEFA' },
  NZL: { en: 'New Zealand', ko: '뉴질랜드', confederation: 'OFC' },
  OMA: { en: 'Oman', ko: '오만', confederation: 'AFC' },
  PAN: { en: 'Panama', ko: '파나마', confederation: 'CONCACAF' },
  PAR: { en: 'Paraguay', ko: '파라과이', confederation: 'CONMEBOL' },
  PER: { en: 'Peru', ko: '페루', confederation: 'CONMEBOL' },
  PHI: { en: 'Philippines', ko: '필리핀', confederation: 'AFC' },
  PLE: { en: 'Palestine', ko: '팔레스타인', confederation: 'AFC' },
  POL: { en: 'Poland', ko: '폴란드', confederation: 'UEFA' },
  POR: { en: 'Portugal', ko: '포르투갈', confederation: 'UEFA' },
  PNG: { en: 'Papua New Guinea', ko: '파푸아뉴기니', confederation: 'OFC' },
  PRK: { en: 'Korea DPR', ko: '북한', confederation: 'AFC' },
  PUR: { en: 'Puerto Rico', ko: '푸에르토리코', confederation: 'CONCACAF' },
  QAT: { en: 'Qatar', ko: '카타르', confederation: 'AFC' },
  ROM: { en: 'Romania', ko: '루마니아', confederation: 'UEFA' },
  RUS: { en: 'Russia', ko: '러시아', confederation: 'UEFA' },
  SAU: { en: 'Saudi Arabia', ko: '사우디아라비아', confederation: 'AFC' },
  RSA: { en: 'South Africa', ko: '남아프리카공화국', confederation: 'CAF' },
  SAM: { en: 'Samoa', ko: '사모아', confederation: 'OFC' },
  SCO: { en: 'Scotland', ko: '스코틀랜드', confederation: 'UEFA' },
  SER: { en: 'Serbia', ko: '세르비아', confederation: 'UEFA' },
  SEN: { en: 'Senegal', ko: '세네갈', confederation: 'CAF' },
  SLV: { en: 'El Salvador', ko: '엘살바도르', confederation: 'CONCACAF' },
  SLO: { en: 'Slovakia', ko: '슬로바키아', confederation: 'UEFA' },
  SOL: { en: 'Solomon Islands', ko: '솔로몬 제도', confederation: 'OFC' },
  SOU: { en: 'South Africa', ko: '남아프리카공화국', confederation: 'CAF' },
  SPA: { en: 'Spain', ko: '스페인', confederation: 'UEFA' },
  SVN: { en: 'Slovenia', ko: '슬로베니아', confederation: 'UEFA' },
  SWE: { en: 'Sweden', ko: '스웨덴', confederation: 'UEFA' },
  SWI: { en: 'Switzerland', ko: '스위스', confederation: 'UEFA' },
  SYR: { en: 'Syria', ko: '시리아', confederation: 'AFC' },
  SUI: { en: 'Switzerland', ko: '스위스', confederation: 'UEFA' },
  TAN: { en: 'Tanzania', ko: '탄자니아', confederation: 'CAF' },
  THA: { en: 'Thailand', ko: '태국', confederation: 'AFC' },
  TJK: { en: 'Tajikistan', ko: '타지키스탄', confederation: 'AFC' },
  TPE: { en: 'Chinese Taipei', ko: '중화 타이베이', confederation: 'AFC' },
  TRI: { en: 'Trinidad and Tobago', ko: '트리니다드 토바고', confederation: 'CONCACAF' },
  TUN: { en: 'Tunisia', ko: '튀니지', confederation: 'CAF' },
  TUR: { en: 'Turkey', ko: '터키', confederation: 'UEFA' },
  UAE: { en: 'United Arab Emirates', ko: '아랍에미리트', confederation: 'AFC' },
  UGA: { en: 'Uganda', ko: '우간다', confederation: 'CAF' },
  UKR: { en: 'Ukraine', ko: '우크라이나', confederation: 'UEFA' },
  UNI: { en: 'United States of America', ko: '미국', confederation: 'CONCACAF' },
  URU: { en: 'Uruguay', ko: '우루과이', confederation: 'CONMEBOL' },
  USA: { en: 'United States', ko: '미국', confederation: 'CONCACAF' },
  UZB: { en: 'Uzbekistan', ko: '우즈베키스탄', confederation: 'AFC' },
  VEN: { en: 'Venezuela', ko: '베네수엘라', confederation: 'CONMEBOL' },
  VAN: { en: 'Vanuatu', ko: '바누아투', confederation: 'OFC' },
  VIE: { en: 'Vietnam', ko: '베트남', confederation: 'AFC' },
  WAL: { en: 'Wales', ko: '웨일스', confederation: 'UEFA' },
  ZAM: { en: 'Zambia', ko: '잠비아', confederation: 'CAF' },
};

export const COMPETITION_NAMES_KO: Record<string, NamedLocalizationEntry> = {
  '1-bundesliga': { name: '분데스리가', shortName: '분데스리가' },
  'african-cup-of-nations-international': { name: '아프리카 네이션스컵', shortName: '네이션스컵' },
  bundesliga: { name: '분데스리가', shortName: '분데스리가' },
  'champions-league': { name: 'UEFA 챔피언스리그', shortName: '챔피언스리그' },
  'copa-america-international': { name: '코파 아메리카', shortName: '코파 아메리카' },
  'copa-del-rey': { name: '코파 델 레이', shortName: '코파 델 레이' },
  'fa-women-s-super-league-women': { name: 'FA 여자 슈퍼리그', shortName: 'FA 여자 슈퍼리그' },
  'fifa-u20-world-cup-international-youth': { name: 'FIFA U-20 월드컵', shortName: 'U-20 월드컵' },
  'fifa-world-cup-international': { name: 'FIFA 월드컵', shortName: '월드컵' },
  'indian-super-league': { name: '인도 슈퍼리그', shortName: '인도 슈퍼리그' },
  laliga: { name: '라리가', shortName: '라리가' },
  'la-liga': { name: '라리가', shortName: '라리가' },
  'liga-profesional': { name: '리가 프로페시오날', shortName: '리가 프로페시오날' },
  ligue1: { name: '리그 1', shortName: '리그 1' },
  'ligue-1': { name: '리그 1', shortName: '리그 1' },
  'major-league-soccer': { name: '메이저리그사커', shortName: 'MLS' },
  'north-american-league': { name: '북미 리그', shortName: '북미 리그' },
  'nwsl-women': { name: 'NWSL', shortName: 'NWSL' },
  pl: { name: '프리미어리그', shortName: '프리미어리그' },
  'premier-league': { name: '프리미어리그', shortName: '프리미어리그' },
  seriea: { name: '세리에 A', shortName: '세리에 A' },
  'serie-a': { name: '세리에 A', shortName: '세리에 A' },
  'uefa-euro-international': { name: 'UEFA 유로', shortName: 'UEFA 유로' },
  'uefa-europa-league': { name: 'UEFA 유로파리그', shortName: '유로파리그' },
  'uefa-women-s-euro-international-women': { name: 'UEFA 여자 유로', shortName: 'UEFA 여자 유로' },
  'women-s-world-cup-international-women': { name: '여자 월드컵', shortName: '여자 월드컵' },
};

export const TEAM_NAMES_KO: Record<string, NamedLocalizationEntry> = {
  '1-fc-heidenheim-1846-germany': { name: '1. FC 하이덴하임 1846', shortName: '하이덴하임' },
  '1-fc-ko-ln-germany': { name: '1. FC 쾰른', shortName: '쾰른' },
  '1-fc-union-berlin-germany': { name: '1. FC 우니온 베를린', shortName: '우니온 베를린' },
  '1-fsv-mainz-05-germany': { name: '1. FSV 마인츠 05', shortName: '마인츠' },
  'acf-fiorentina-italy': { name: 'ACF 피오렌티나', shortName: '피오렌티나' },
  'ac-pisa-1909-italy': { name: 'AC 피사 1909', shortName: '피사' },
  'afc-ajax-netherlands': { name: '아약스', shortName: '아약스' },
  'afc-bournemouth-england': { name: '본머스', shortName: '본머스' },
  'aj-auxerre-france': { name: 'AJ 오세르', shortName: '오세르' },
  anderlecht: { name: '안데를레흐트', shortName: '안데를레흐트' },
  'angers-sco-france': { name: '앙제 SCO', shortName: '앙제' },
  'apoel-nicosia': { name: '아포엘 니코시아', shortName: '아포엘' },
  arsenal: { name: '아스널', shortName: '아스널' },
  'arsenal-fc-england': { name: '아스널', shortName: '아스널' },
  atletico: { name: '아틀레티코 마드리드', shortName: '아틀레티코 마드리드' },
  'atalanta-bc-italy': { name: '아탈란타 BC', shortName: '아탈란타' },
  'az-alkmaar': { name: 'AZ 알크마르', shortName: 'AZ' },
  barcelona: { name: '바르셀로나', shortName: '바르셀로나' },
  'bayer-leverkusen-germany': { name: '바이어 04 레버쿠젠', shortName: '레버쿠젠' },
  'bayern-munich': { name: '바이에른 뮌헨', shortName: '바이에른 뮌헨' },
  'bes-iktas': { name: '베식타시', shortName: '베식타시' },
  bayern: { name: '바이에른 뮌헨', shortName: '바이언' },
  'bodo-glimt': { name: '보되/글림트', shortName: '보되/글림트' },
  'borac-banja-luka': { name: '보라츠 반야루카', shortName: '보라츠' },
  'borussia-mo-nchengladbach-germany': { name: '보루시아 묀헨글라트바흐', shortName: '묀헨글라트바흐' },
  'botev-plovdiv': { name: '보테프 플로브디프', shortName: '보테프' },
  'brentford-fc-england': { name: '브렌트퍼드', shortName: '브렌트퍼드' },
  'brighton-and-hove-albion-fc-england': { name: '브라이턴 앤드 호브 앨비언', shortName: '브라이턴' },
  'burnley-fc-england': { name: '번리', shortName: '번리' },
  'cagliari-calcio-italy': { name: '칼리아리', shortName: '칼리아리' },
  'celje': { name: '첼레', shortName: '첼레' },
  chelsea: { name: '첼시', shortName: '첼시' },
  'club-atle-tico-de-madrid-spain': { name: '아틀레티코 마드리드', shortName: '아틀레티코' },
  'club-brugge-kv-belgium': { name: '클럽 브뤼헤', shortName: '브뤼헤' },
  'como-1907-italy': { name: '코모 1907', shortName: '코모' },
  'corvinul-hunedoara': { name: '코르비눌 후네도아라', shortName: '코르비눌' },
  'crystal-palace-fc-england': { name: '크리스털 팰리스', shortName: '크리스털 팰리스' },
  'deportivo-alave-s-spain': { name: '알라베스', shortName: '알라베스' },
  'deportivo-alaves-spain': { name: '알라베스', shortName: '알라베스' },
  'dinamo-minsk': { name: '디나모 민스크', shortName: '디나모 민스크' },
  dortmund: { name: '보루시아 도르트문트', shortName: '도르트문트' },
  'dynamo-kyiv': { name: '디나모 키이우', shortName: '디나모 키이우' },
  'fc-k-benhavn-denmark': { name: 'FC 코펜하겐', shortName: '코펜하겐' },
  'fc-lorient-france': { name: 'FC 로리앙', shortName: '로리앙' },
  'fc-lugano': { name: 'FC 루가노', shortName: '루가노' },
  'fc-metz-france': { name: 'FC 메츠', shortName: '메츠' },
  'fc-midtjylland': { name: 'FC 미트윌란', shortName: '미트윌란' },
  'fc-nantes-france': { name: 'FC 낭트', shortName: '낭트' },
  'fc-st-pauli-1910-germany': { name: 'FC 장크트파울리', shortName: '장크트파울리' },
  fcsb: { name: 'FCSB', shortName: 'FCSB' },
  'fenerbahc-e': { name: '페네르바체', shortName: '페네르바체' },
  'ferencvarosi-tc': { name: '페렌츠바로시 TC', shortName: '페렌츠바로시' },
  'fk-bod-glimt-norway': { name: 'FK 보되/글림트', shortName: '보되/글림트' },
  'fk-kairat-kazakhstan': { name: 'FK 카이라트', shortName: '카이라트' },
  'fk-partizan': { name: 'FK 파르티잔', shortName: '파르티잔' },
  'fk-tobol-kostanay': { name: 'FK 토볼 코스타나이', shortName: '토볼' },
  'galatasaray': { name: '갈라타사라이', shortName: '갈라타사라이' },
  'galatasaray-sk-turkey': { name: '갈라타사라이', shortName: '갈라타사라이' },
  'genoa-cfc-italy': { name: '제노아', shortName: '제노아' },
  'hellas-verona-fc-italy': { name: '헬라스 베로나', shortName: '베로나' },
  'heart-of-midlothian': { name: '하트 오브 미들로디언', shortName: '하츠' },
  'hnk-rijeka': { name: 'HNK 리예카', shortName: '리예카' },
  'if-elfsborg': { name: 'IF 엘프스보리', shortName: '엘프스보리' },
  'juventus-fc-italy': { name: '유벤투스', shortName: '유벤투스' },
  inter: { name: '인테르', shortName: '인테르' },
  'fc-internazionale-milano-italy': { name: '인터 밀란', shortName: '인테르' },
  'inter-miami-united-states-of-america': { name: '인터 마이애미', shortName: '인터 마이애미' },
  'jagiellonia': { name: '야기엘로니아 비아위스토크', shortName: '야기엘로니아' },
  'ki-klaksvik': { name: 'KI 클락스비크', shortName: '클락스비크' },
  'kilmarnock': { name: '킬마녹', shortName: '킬마녹' },
  'kryvbas-kr': { name: '크리우바스 KR', shortName: '크리우바스' },
  'lask-linz': { name: 'LASK 린츠', shortName: 'LASK 린츠' },
  'le-havre-ac-france': { name: '르아브르 AC', shortName: '르아브르' },
  juventus: { name: '유벤투스', shortName: '유벤투스' },
  'levante-ud-spain': { name: '레반테 UD', shortName: '레반테' },
  leipzig: { name: 'RB 라이프치히', shortName: '라이프치히' },
  'lincoln-red-imps-fc': { name: '링컨 레드 임프스 FC', shortName: '링컨 레드 임프스' },
  leverkusen: { name: '바이어 레버쿠젠', shortName: '레버쿠젠' },
  'llapi': { name: '야피', shortName: '야피' },
  liverpool: { name: '리버풀', shortName: '리버풀' },
  'malmo-ff': { name: '말뫼 FF', shortName: '말뫼' },
  mancity: { name: '맨체스터 시티', shortName: '맨시티' },
  'olympique-de-marseille-france': { name: '마르세유', shortName: '마르세유' },
  'olympique-lyonnais-france': { name: '올랭피크 리옹', shortName: '리옹' },
  'ol-reign-united-states-of-america': { name: 'OL 레인', shortName: 'OL 레인' },
  'olympiakos-piraeus': { name: '올림피아코스', shortName: '올림피아코스' },
  'pae-olympiakos-sfp-greece': { name: '올림피아코스', shortName: '올림피아코스' },
  'pafos': { name: '파포스', shortName: '파포스' },
  'paphos-fc-cyprus': { name: '파포스 FC', shortName: '파포스' },
  'paneve-z-ys': { name: '파네베지스', shortName: '파네베지스' },
  'paris-fc-france': { name: '파리 FC', shortName: '파리 FC' },
  'parma-calcio-1913-italy': { name: '파르마', shortName: '파르마' },
  'paks': { name: '팍시', shortName: '팍시' },
  'paok': { name: 'PAOK', shortName: 'PAOK' },
  'petrocub': { name: '페트로쿠브', shortName: '페트로쿠브' },
  milan: { name: 'AC 밀란', shortName: 'AC 밀란' },
  'plzen': { name: '플젠', shortName: '플젠' },
  monaco: { name: 'AS 모나코', shortName: 'AS 모나코' },
  'qarabag': { name: '카라바흐', shortName: '카라바흐' },
  'qarabag-ag-dam-fk-azerbaijan': { name: '카라바흐 아그담 FK', shortName: '카라바흐' },
  'racing-club-de-lens-france': { name: 'RC 랑스', shortName: '랑스' },
  'rangers': { name: '레인저스', shortName: '레인저스' },
  'rapid-vienna': { name: '라피드 빈', shortName: '라피드 빈' },
  'rayo-vallecano-de-madrid-spain': { name: '라요 바예카노', shortName: '라요' },
  'real-oviedo-spain': { name: '레알 오비에도', shortName: '오비에도' },
  'ri-gas-fs': { name: '리가스 FS', shortName: '리가스 FS' },
  'royale-union-saint-gilloise-belgium': { name: '위니옹 생질루아즈', shortName: '위니옹 생질루아즈' },
  'ruz-omberok': { name: '루좀베로크', shortName: '루좀베로크' },
  'sc-braga': { name: 'SC 브라가', shortName: '브라가' },
  'sc-freiburg-germany': { name: 'SC 프라이부르크', shortName: '프라이부르크' },
  'servette-fc': { name: '세르베트 FC', shortName: '세르베트' },
  napoli: { name: '나폴리', shortName: '나폴리' },
  'sevilla-fc-spain': { name: '세비야', shortName: '세비야' },
  'shamrock-rovers': { name: '셰임록 로버스', shortName: '셰임록 로버스' },
  'sheriff-tiraspol': { name: '셰리프 티라스폴', shortName: '셰리프' },
  'silkeborg': { name: '실케보르', shortName: '실케보르' },
  'sk-slavia-praha-czech-republic': { name: '슬라비아 프라하', shortName: '슬라비아 프라하' },
  'sporting-clube-de-portugal-portugal': { name: '스포르팅 CP', shortName: '스포르팅' },
  'sport-lisboa-e-benfica-portugal': { name: '벤피카', shortName: '벤피카' },
  'ssc-napoli-italy': { name: '나폴리', shortName: '나폴리' },
  'ss-lazio-italy': { name: '라치오', shortName: '라치오' },
  'stade-brestois-29-france': { name: '스타드 브레스트 29', shortName: '브레스트' },
  'stade-rennais-fc-1901-france': { name: '스타드 렌 FC 1901', shortName: '렌' },
  psg: { name: '파리 생제르맹', shortName: 'PSG' },
  'psv-netherlands': { name: 'PSV 에인트호번', shortName: 'PSV' },
  realmadrid: { name: '레알 마드리드', shortName: '레알 마드리드' },
  'torino-fc-italy': { name: '토리노', shortName: '토리노' },
  '1899-hoffenheim': { name: '1899 호펜하임', shortName: '호펜하임' },
  'toulouse-fc-france': { name: '툴루즈 FC', shortName: '툴루즈' },
  'the-new-saints': { name: '더 뉴 세인츠', shortName: '더 뉴 세인츠' },
  'trabzonspor': { name: '트라브존스포르', shortName: '트라브존스포르' },
  'tsc-backa-topola': { name: 'TSC 바츠카 토폴라', shortName: '바츠카 토폴라' },
  'twente': { name: '트벤테', shortName: '트벤테' },
  'udinese-calcio-italy': { name: '우디네세', shortName: '우디네세' },
  'ue-santa-coloma': { name: 'UE 산타 콜로마', shortName: '산타 콜로마' },
  'union-st-gilloise': { name: '위니옹 생질루아즈', shortName: '위니옹 생질루아즈' },
  'us-cremonese-italy': { name: '크레모네세', shortName: '크레모네세' },
  'us-lecce-italy': { name: '레체', shortName: '레체' },
  'us-sassuolo-calcio-italy': { name: '사수올로', shortName: '사수올로' },
  'vojvodina': { name: '보이보디나', shortName: '보이보디나' },
  'wisla-krakow': { name: '비스와 크라쿠프', shortName: '비스와 크라쿠프' },
  'cercle-brugge': { name: '세르클러 브뤼허', shortName: '세르클러 브뤼허' },
  'ludogorets': { name: '루도고레츠', shortName: '루도고레츠' },
  'maccabi-petah-tikva': { name: '마카비 페타티크바', shortName: '마카비 페타티크바' },
  'maccabi-tel-aviv': { name: '마카비 텔아비브', shortName: '마카비 텔아비브' },
  'maribor': { name: '마리보르', shortName: '마리보르' },
  'molde': { name: '몰데', shortName: '몰데' },
  'nice': { name: '니스', shortName: '니스' },
  'nottingham-forest-fc-england': { name: '노팅엄 포리스트', shortName: '노팅엄 포리스트' },
  'slavia-praha': { name: '슬라비아 프라하', shortName: '슬라비아 프라하' },
  sevilla: { name: '세비야', shortName: '세비야' },
  'zira': { name: '지라', shortName: '지라' },
  'werder-bremen-germany': { name: '베르더 브레멘', shortName: '베르더 브레멘' },
};
